# Generated by Django 4.1.7 on 2023-04-06 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_published', models.DateField(blank=True, default=datetime.datetime(2023, 4, 6, 18, 48, 30, 178990, tzinfo=datetime.timezone.utc))),
                ('post_text', models.CharField(max_length=10000000)),
            ],
        ),
    ]
