# Generated by Django 4.1.7 on 2023-04-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0004_alter_blogposts_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='date_published',
            field=models.DateField(verbose_name=datetime.datetime(2023, 4, 6, 19, 4, 8, 75108, tzinfo=datetime.timezone.utc)),
        ),
    ]
